'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowUpRight, Check, Clock, MapPin, Video } from 'lucide-react'
import { useRouter } from 'next/navigation'

type Service={id:string;slug:string;name:string;short_description:string;description:string;duration_minutes:number;price:number;currency:string}
type Settings={zoom_platform?:string;location_label?:string;location_details?:string}|null

export default function BookingForm({services,settings}:{services:Service[];settings:Settings}) {
 const router=useRouter(); const [service,setService]=useState(services[0]?.id??''); const [mode,setMode]=useState<'zoom'|'in_person'>('zoom'); const [date,setDate]=useState(''); const [slot,setSlot]=useState(''); const [slots,setSlots]=useState<string[]>([]); const [name,setName]=useState(''); const [question,setQuestion]=useState(''); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState(false)
 const selected=useMemo(()=>services.find(s=>s.id===service),[services,service])
 async function chooseDate(value:string){setDate(value);setSlot('');setError('');if(!value||!service)return;const r=await fetch(`/api/availability?date=${value}&service_id=${service}`);const d=await r.json();if(!r.ok)setError(d.error||'Could not load times.');else setSlots(d.slots??[])}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!service||!date||!slot||!name.trim()||!question.trim()){setError('Complete the reading, time, name, and question.');return}setBusy(true);const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service_id:service,session_type:mode,requested_start:slot,customer_name:name,customer_question:question,customer_notes:notes})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Could not create request.');return}setDone(true);router.refresh()}
 if(done)return <section className="booking-success"><div className="success-icon"><Check size={22}/></div><p className="eyebrow">REQUEST RECEIVED</p><h2>Your question is with Rev.</h2><p>The request is private and will be reviewed personally. You can follow its status from your dashboard.</p><a className="button button-primary" href="/dashboard">Open dashboard <ArrowUpRight size={16}/></a></section>
 const minDate=new Date(Date.now()+24*3600000).toISOString().slice(0,10)
 return <form className="booking-form" onSubmit={submit}><div className="booking-step"><span>01</span><div><p className="eyebrow">THE READING</p><h2>What do you want to ask?</h2></div></div><div className="service-grid">{services.map(s=><button type="button" key={s.id} className={`service-option ${service===s.id?'selected':''}`} onClick={()=>{setService(s.id);if(date)chooseDate(date)}}><span>{s.name}</span><strong>{s.currency==='INR'?'₹':''}{Number(s.price).toLocaleString()}</strong><p>{s.short_description}</p><small><Clock size={13}/> {s.duration_minutes} min</small></button>)}</div><div className="booking-step"><span>02</span><div><p className="eyebrow">THE FORMAT</p><h2>How should we meet?</h2></div></div><div className="mode-grid"><button type="button" className={mode==='zoom'?'selected':''} onClick={()=>setMode('zoom')}><Video size={17}/><b>{settings?.zoom_platform||'Zoom'}</b><span>Private video session</span></button><button type="button" className={mode==='in_person'?'selected':''} onClick={()=>setMode('in_person')}><MapPin size={17}/><b>{settings?.location_label||'In person'}</b><span>{settings?.location_details||'Location shared after confirmation'}</span></button></div><div className="booking-step"><span>03</span><div><p className="eyebrow">THE TIME</p><h2>When are you free?</h2></div></div><label>Date<input type="date" min={minDate} value={date} onChange={e=>chooseDate(e.target.value)} required/></label>{date&&<div className="slot-grid">{slots.length?slots.map(s=><button type="button" key={s} className={slot===s?'selected':''} onClick={()=>setSlot(s)}>{new Date(s).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'})}</button>):<p className="empty-slots">No available times on this date.</p>}</div>}<div className="booking-step"><span>04</span><div><p className="eyebrow">THE QUESTION</p><h2>Give the reading somewhere to begin.</h2></div></div><label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={120} required placeholder="Your name"/></label><label>Your question<textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={4000} required rows={5} placeholder="What are you really trying to understand?"/></label><label>Anything else <span className="muted">(optional)</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={4000} rows={3} placeholder="Context, timing, or anything Rev should know."/></label>{error&&<p className="auth-error">{error}</p>}<button className="button button-primary submit-booking" disabled={busy}>{busy?'Sending request…':'Request this private reading'} <ArrowUpRight size={16}/></button><p className="booking-fine">No payment is taken here. Rev reviews each request and confirms the session personally.</p></form>
}
