import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Link from 'next/link'

export default async function Dashboard(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login')
 const [{data:bookings},{data:services},{data:settings}]=await Promise.all([
  supabase.from('bookings').select('id,status,requested_start,session_type,customer_name,services(name)').order('requested_start',{ascending:true}).limit(20),
  supabase.from('services').select('id,name,duration_minutes,price,is_active').order('sort_order'),
  supabase.from('site_settings').select('display_name,location_label,zoom_platform').single(),
 ])
 const isReader=user.app_metadata?.role==='reader'
 return <main className="dash"><header className="dash-nav"><Link href="/" className="wordmark">REV<span>.</span></Link><span>{isReader?'READER CONSOLE':'YOUR ROOM'}</span></header><section className="dash-wrap"><div className="dash-hero"><div><p className="eyebrow">{isReader?'PRIVATE READER DASHBOARD':'PRIVATE DASHBOARD'}</p><h1>{isReader?'The room, behind the room.':'Your readings.'}</h1></div><form action="/auth/signout" method="post"><button className="button button-quiet">Sign out</button></form></div>{isReader?<><div className="dash-grid"><div className="dash-panel wide"><p className="panel-label">UPCOMING REQUESTS</p>{bookings?.length?<div className="rows">{bookings.map((b:any)=><div className="row" key={b.id}><span>{new Date(b.requested_start).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span><b>{b.customer_name||'Anonymous client'}</b><em>{b.status}</em></div>)}</div>:<p className="empty">No requests yet. The room is quiet.</p>}</div><div className="dash-panel"><p className="panel-label">SETUP</p><p className="setting-line">Display <b>{settings?.display_name??'Rev'}</b></p><p className="setting-line">Zoom <b>{settings?.zoom_platform??'Not set'}</b></p><p className="setting-line">In person <b>{settings?.location_label||'Not set'}</b></p></div></div><div className="dash-panel"><p className="panel-label">SERVICES</p><div className="rows">{services?.map((s:any)=><div className="row" key={s.id}><b>{s.name}</b><span>{s.duration_minutes} min · {s.price} INR</span><em>{s.is_active?'live':'hidden'}</em></div>)}</div></div></>:<div className="dash-grid"><div className="dash-panel wide"><p className="panel-label">YOUR REQUESTS</p>{bookings?.length?<div className="rows">{bookings.map((b:any)=><div className="row" key={b.id}><span>{new Date(b.requested_start).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span><b>{(b.services as any)?.name||'Reading'}</b><em>{b.status}</em></div>)}</div>:<div className="empty"><p>You haven't requested a reading yet.</p><Link className="button button-primary" href="/#readings">Explore readings</Link></div>}</div></div>}</section></main>
}
