'use client'

import { useState } from 'react'
import { Check, Save, X } from 'lucide-react'
import { useRouter } from 'next/navigation'

type Booking={id:string;status:string;requested_start:string;requested_end:string;session_type:string;customer_name:string;customer_phone?:string|null;customer_question:string;customer_notes:string;reader_notes:string;meeting_link?:string|null;meeting_location?:string|null;services?:{name:string}|null}
type Service={id:string;name:string;duration_minutes:number;price:number;currency:string;is_active:boolean}

aasync function noop(){}

export default function ReaderConsole({bookings,services}:{bookings:Booking[];services:Service[]}) {
 const router=useRouter(); const [selected,setSelected]=useState<Booking|null>(bookings[0]??null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 async function update(id:string,patch:Record<string,unknown>){setBusy(true);setMessage('');const r=await fetch('/api/reader/bookings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch})});const d=await r.json();setBusy(false);if(!r.ok){setMessage(d.error||'Could not update.');return false}setMessage('Saved.');router.refresh();return true}
 return <div className="reader-console"><div className="reader-bookings"><p className="panel-label">REQUESTS</p>{bookings.length?<div className="reader-list">{bookings.map(b=><button type="button" key={b.id} className={`reader-item ${selected?.id===b.id?'selected':''}`} onClick={()=>{setSelected(b);setMessage('')}}><span>{new Date(b.requested_start).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span><b>{b.customer_name}</b><em>{b.status}</em><small>{b.services?.name||'Reading'}</small></button>)}</div>:<p className="empty">No requests yet.</p>}</div>{selected&&<div className="reader-detail"><div className="detail-head"><div><p className="panel-label">PRIVATE REQUEST</p><h2>{selected.customer_name}</h2><p>{selected.services?.name||'Reading'} · {new Date(selected.requested_start).toLocaleString('en-IN',{dateStyle:'full',timeStyle:'short'})}</p></div><span className={`status status-${selected.status}`}>{selected.status}</span></div><div className="detail-question"><p className="panel-label">QUESTION</p><p>{selected.customer_question}</p>{selected.customer_notes&&<><p className="panel-label">CONTEXT</p><p>{selected.customer_notes}</p></>}</div><div className="action-row"><button disabled={busy} onClick={()=>update(selected.id,{status:'confirmed'})}><Check size={14}/> Confirm</button><button disabled={busy} onClick={()=>update(selected.id,{status:'declined'})}><X size={14}/> Decline</button><button disabled={busy} onClick={()=>update(selected.id,{status:'completed'})}>Mark complete</button></div><div className="reader-fields"><label>Meeting link<input defaultValue={selected.meeting_link||''} onBlur={e=>update(selected.id,{meeting_link:e.target.value})} placeholder="https://zoom.us/..."/></label><label>Meeting location<input defaultValue={selected.meeting_location||''} onBlur={e=>update(selected.id,{meeting_location:e.target.value})} placeholder="Only if meeting in person"/></label><label>Private reader notes<textarea defaultValue={selected.reader_notes||''} onBlur={e=>update(selected.id,{reader_notes:e.target.value})} rows={5} placeholder="Private notes for Rev"/></label></div>{message&&<p className="save-message"><Save size={13}/> {message}</p>}</div>}<div className="reader-services"><p className="panel-label">SERVICES</p>{services.map(s=><div className="service-row" key={s.id}><b>{s.name}</b><span>{s.duration_minutes} min · {s.price} {s.currency}</span><em>{s.is_active?'LIVE':'HIDDEN'}</em></div>)}</div></div>
}
